### PR TITLE
Fix test failure due to typo in resource filename

### PR DESCRIPTION
**Pull request by mnemonicflow**
onBuildDeeplink_whenNoNicknameOrAddressProvided_shouldNotHaveNicknameAndAddress test was failing in RequestDeeplinkTest class due to FileNotFoundException

All tests are running after renaming the no_nickname_or_Address filename to no_nickname_or_address

### CODE REVIEW

**Comment by hzsweers** [comment]
lgtm

**Comment by mnemonicflow** [comment]
@hzsweers @itstexter Does Uber accept contributions through GitHub? I see that all Uber GitHub repositories are very low on traffic regarding input from Uber developers.

**Comment by itstexter** [comment]
Sorry for the delay on this! Totally lost track of it.  

Thanks so much for the catch!  For some reason that test is passing for me, I'll have to be more careful on getting these passing in different environments.

@mnemonicflow if you could sign our [Uber CLA](https://docs.google.com/a/uber.com/forms/d/1pAwS_-dA1KhPlfxzYLBqK6rsSWwRwH95OCCZrcsY5rk/viewform) I can go ahead and get this merged!

**Comment by mnemonicflow** [comment]
@itstexter I have signed the Uber CLA.

If you are on Windows and using the NTFS filesystem then the reason may be this: The filesystem is case sensitive due to [POSIX compliance](https://support.microsoft.com/en-us/kb/100625), but the operating system does not support file names that only differ by case sensitivity, however it is possible to create those files with [lower level system calls](http://www.osronline.com/article.cfm?id=91)
On UNIX systems (GNU/Linux, Mac OS, FreeBSD, etc.) the filesystems are usually case sensitive.
See http://superuser.com/a/364062

The file read by the test is referenced with an all lowercase name:
```
sdk/src/test/java/com/uber/sdk/android/rides/RequestDeeplinkTest.java
138:        String expectedUri = readUriResourceWithUserAgentParam("src/test/resources/deeplinkuris/no_nickname_or_address",
```

However on the filesystem the file is actually named with an uppercase "A": src/test/resources/deeplinkuris/no_nickname_or_**A**ddress , this means that on:
- Windows: test will run successfully, because the JVM that runs the code and which internally makes Win32 syscalls to actually access the file doesn't differentiate between file's case sensitivity.
- UNIX systems: test will fail

**Comment by itstexter** [comment]
Thanks so much @mnemonicflow !

**Pull request merged**
