### PR TITLE
add deprecated "onReceivedError" to solve compatibility issue

### PR DESCRIPTION
**Pull request by strooonger**
Description: reserve both new and deprecated "onReceivedError" to ensure it works well in all API level.

Related issue(s): #105

### CODE REVIEW

**Comment by strooonger** [comment]
Travis CI build is not successful because I cannot say yes to agree the license. Could you help fix it please?

**Comment by tyvsmith** [comment]
Thanks @strooonger, will take a look into the CI issue.

**Comment by tyvsmith** [comment]
Can you try rebasing? I'm not seeing CI issues on other diffs. Thanks!

**Comment by tyvsmith** [comment]
The licenses should be configured correctly for Travis. I'm wondering if it's related to the target API call changing it somehow. I'll investigate the failure.

**Comment by tyvsmith** [comment]
Cherry picked your commit and drove it through https://github.com/uber/rides-android-sdk/pull/113

**Pull request closed without merging**
