### PR TITLE
Fix typos in README

### PR DESCRIPTION
**Pull request by joebowbeer**
Applies ``s/RequestButton/RideRequestButton/`` spelling correction.

### CODE REVIEW

**Comment by arogal** [comment]
Hi Joe. Please sign https://docs.google.com/a/uber.com/forms/d/1pAwS_-dA1KhPlfxzYLBqK6rsSWwRwH95OCCZrcsY5rk/viewform for us to pull this change. Thanks!

**Comment by joebowbeer** [comment]
done

**Comment by arogal** [comment]
Thanks. This change will be made visible in our next release.

**Comment by tyvsmith** [comment]
Thanks for your contribution! Your changes should be seen in the latest update.

**Pull request merged**
